"""
Matrix exporter — extracts trained unitary matrices and generates FPGA handoff artifacts.

Outputs (saved to results/matrices/):
  - gate_matrices.json          raw float complex matrices
  - gate_matrices_fixed16.json  quantized to ap_fixed<16,4>
  - hls_constants.cpp           paste-ready Xilinx Vitis HLS C++ constants
  - quantization_report.txt     per-matrix quantization error summary
"""

import json
import logging
import math
from pathlib import Path

import numpy as np
import torch

from .fixed_point import quantize_matrix, matrix_to_hls_cpp

logger = logging.getLogger(__name__)


class MatrixExporter:
    """Extracts and exports unitary matrices from a trained HybridQCNN model."""

    def __init__(self, output_dir: str = "results/matrices"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def export(self, model, tag: str = "default") -> dict:
        """
        Extract all gate matrices from the trained VQC and save artifacts.

        Args:
            model: trained HybridQCNN instance
            tag:   identifier string (e.g. "5xor")

        Returns:
            dict with all exported data
        """
        model.eval()
        raw_matrices = model.vqc.get_unitary_matrices()

        quantized = {}
        cpp_blocks = [
            "// Auto-generated by AS-QCNN-PUF-Auth matrix exporter",
            "// Paste into Xilinx Vitis HLS project",
            "// Format: ap_fixed<16,4> — 1 sign | 3 int | 12 frac bits",
            "",
            '#include "ap_fixed.h"',
            "typedef ap_fixed<16,4> q_scalar;",
            "typedef struct { q_scalar real; q_scalar imag; } q_complex;",
            "",
        ]

        errors = []
        for layer_key, qubits in raw_matrices.items():
            quantized[layer_key] = {}
            layer_idx = layer_key.split("_")[1]

            for qubit_key, U_list in qubits.items():
                U = np.array([[complex(r[0], r[1]) for r in row] for row in U_list])
                q_result = quantize_matrix(U)
                quantized[layer_key][qubit_key] = q_result
                errors.append(q_result["max_error"])

                qubit_idx = qubit_key.split("_")[1]
                var_name = f"U_L{layer_idx}_Q{qubit_idx}"
                cpp_blocks.append(matrix_to_hls_cpp(U, var_name))
                cpp_blocks.append("")

        # Save raw float matrices
        raw_path = self.output_dir / f"gate_matrices_{tag}.json"
        with open(raw_path, "w") as f:
            json.dump(raw_matrices, f, indent=2)

        # Save fixed-point matrices
        fixed_path = self.output_dir / f"gate_matrices_fixed16_{tag}.json"
        with open(fixed_path, "w") as f:
            json.dump(quantized, f, indent=2)

        # Save HLS C++ snippet
        cpp_path = self.output_dir / f"hls_constants_{tag}.cpp"
        cpp_path.write_text("\n".join(cpp_blocks))

        # Save quantization report
        report_lines = [
            f"Quantization Report — {tag}",
            f"Format: ap_fixed<16,4>  |  Resolution: {2**-12:.6f}",
            f"Layers: {len(raw_matrices)}  |  Qubits/layer: {model.vqc.n_qubits}",
            f"Mean max error: {np.mean(errors):.6f}",
            f"Worst max error: {np.max(errors):.6f}",
            f"Best max error:  {np.min(errors):.6f}",
            "",
            "Per-matrix errors:",
        ]
        for layer_key, qubits in quantized.items():
            for qubit_key, q in qubits.items():
                report_lines.append(f"  {layer_key}/{qubit_key}: {q['max_error']:.6f}")

        report_path = self.output_dir / f"quantization_report_{tag}.txt"
        report_path.write_text("\n".join(report_lines))

        logger.info(f"Exported matrices to {self.output_dir}")
        logger.info(f"Mean quantization error: {np.mean(errors):.6f}")
        logger.info(f"HLS constants: {cpp_path}")

        return {
            "raw_matrices": raw_matrices,
            "quantized": quantized,
            "mean_error": float(np.mean(errors)),
            "max_error": float(np.max(errors)),
        }
